# Generated by Django 5.0 on 2026-09-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('period', 'Period Reminder'), ('fertile_window', 'Fertile Window Reminder'), ('daily_log', 'Daily Log Reminder'), ('custom', 'Custom Reminder')], max_length=20)),
                ('days_before', models.IntegerField(default=2, help_text='Days before period/fertile window to trigger reminder')),
                ('time_of_day', models.TimeField(default='08:00:00')),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('custom_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'db_table': 'reminders',
                'ordering': ['reminder_type', '-created_at'],
            },
        ),
    ]
