# Generated by Django 5.0 on 2026-09-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of period (cycle start)')),
                ('end_date', models.DateField(blank=True, help_text='First day of next period (cycle end — set when next cycle begins)', null=True)),
                ('cycle_length', models.IntegerField(blank=True, help_text='Computed: end_date - start_date in days', null=True)),
                ('period_start', models.DateField(help_text='First day of menstrual bleeding')),
                ('period_end', models.DateField(blank=True, help_text='Last day of bleeding', null=True)),
                ('period_duration', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='True for the current ongoing cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'db_table': 'cycles',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FlowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intensity', models.CharField(choices=[('spotting', 'Spotting'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=20)),
                ('color', models.CharField(blank=True, choices=[('bright_red', 'Bright Red'), ('dark_red', 'Dark Red'), ('brown', 'Brown'), ('pink', 'Pink'), ('orange', 'Orange')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to='cycles.cycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flow_logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
